### ISSUE TITLE
Hello from Grafana Pandas Datasource

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-pandas-datasource#1]
Dear @linar-jether,

we just took the chance to upload your gist from [1] into a dedicated repository. We believe that would be a great help to the community. Thanks a stack for conceiving this fine piece of software the other day!

With kind regards,
Andreas.

[1] https://gist.github.com/linar-jether/95ff412f9d19fdf5e51293eb0c09b850

**Comment by amotl** [comment]
Hi @linar-jether.

Regarding licensing, shall we put this under the same license as Grafana itself [1]? That would happen to be the Apache-2.0 License.

With kind regards,
Andreas.

[1] https://github.com/grafana/grafana

**Comment by linar-jether** [comment]
Hi Andreas, 

I appreciate the initiative, hopefully it would make it easier to extend the datasource's functionality :)

License seems fine to me, thank you for asking.

Please feel free to contact me if you need any help in maintaining this

Best regards,
Linar

**Comment by amotl** [comment]
Hi Linar,

thanks for your quick response. I've just added a LICENSE file and also added you as a member to this repository with maintainer level privileges.

I hope to be able to add some thoughts from our pen to the code base in order to generalize it and maybe even publish it as a package to PyPI. Saying that, I will be more than happy if we could explore this journey together.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi Linar,

the package has been overhauled and just been published to PyPI [1]. Kudos again to you for bringing this into the world the other day. Enjoy!

With kind regards,
Andreas.

[1] https://pypi.org/project/grafana-pandas-datasource/
