### ISSUE TITLE
Proposal: Change license to AGPLv3

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-pandas-datasource#8]
Hi @linar-jether,

in order to follow Grafana's licensing change [1], I would also like to relicense the source code in this repository to the AGPL-3.0 license, as we also did at https://github.com/panodata/panodata-map-panel/issues/116 and https://github.com/panodata/panodata-map-panel/pull/121. On this matter, I would like to humbly ask you for acknowledgement or objections.

With kind regards,
Andreas.

[1] https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/

**Comment by linar-jether** [comment]
Sure, fine by me.

**Comment by amotl** [comment]
Thank you. I've implemented it with cb53fd5238.
